version: '3.6'
services:
  jgw:
    build:
      context: jgw
      dockerfile: Dockerfile
    restart: always
    ports: 
      - ${JAVA_GATEWAY}:55555
    volumes:
      - ./profile:/irisdev/profile
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        JAVA_GATEWAY_PORT: ${JAVA_GATEWAY}
        JAVA_GATEWAY_HOST: jgw
        FHIR_TERMINOLOGY_SERVER: ${FHIR_TERMINOLOGY_SERVER}
        FHIR_IG_LIST: /irisdev/profile
    restart: always
    command: --check-caps false
    ports: 
      - 32782:1972
      - 32783:52773
      - 32784:53773
    command: 
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
